name: Go Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17" # Use the correct Go version

      - name: Build and test dedupe
        working-directory: dedupe
        run: |
          go build -v .
          go test -v .

      - name: Build and test txtchecker
        working-directory: txtchecker
        run: |
          go build -v .
          go test -v .
