name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17" # Use the correct Go version

      - name: Build txtchecker
        working-directory: ./txtchecker
        run: go build -v .

      - name: Test txtchecker
        working-directory: ./txtchecker
        run: go test -v .
